project:
  type: website
  output-dir: docs
  resources:
    - data/
    - images/

website:
  title: "EOH 635: Environmental Epidemiology Methods"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lesson1.qmd
        text: "Lesson 1: Intro to R"
      - href: lesson2.qmd
        text: "Lesson 2: Conceptual Frameworks"
      - href: lesson3.qmd
        text: "Lesson 3: EDA & Cleaning"
      - href: lesson4.qmd
        text: "Lesson 4: Exposure Assessment"
      - href: lesson5.qmd
        text: "Lesson 5: Regression & Linearity"
      - href: codebook.qmd
        text: "Codebook"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
